# Generated by Django 4.2.6 on 2023-10-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_todo_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_time',
            new_name='time',
        ),
    ]
